### ISSUE TITLE
Major Request - Place Config either in world folder or config folder (All versions affected.)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [DNAlchemist/minecraft-skinny#1]
I can't use this mod. I am not sure how to setup this mod. I am not sure what to configure. Right now the mod is convoluted for most mid to low tier users. Please either make a video tutorial or explain in much greater detail how this functions.

**Comment by DNAlchemist** [comment]
Are you using a dedicated server?
Configuring server.properties is a standard server configuration procedure for any mod and server itself as well.
Or do you need instructions on how to configure the HTTP server with skins?

**Comment by P3rf3ctXZer0** [comment]
Option 2 please

**Comment by DNAlchemist** [comment]
You can use GitHub as an HTTP server.
For example:
1. Create repo with name **minecraft_skins**
2. Put skin **player.png** into root folder in your repo
3. Set URL in the server.properties to https://raw.githubusercontent.com/P3rf3ctXZer0/minecraft_skins
4. A user with the nickname **player** will get skin **player.png**.

*Each png file that falls into this repository will be associated with the player's name.*

**Comment by P3rf3ctXZer0** [comment]
nice thank you :D
