### ISSUE TITLE
Crash Rendering entity in world

### ISSUE THREAD

**Issue by MacKey-255** [DNAlchemist/minecraft-skinny#3]
Hello, with Minecraft version 1.12.2 forge 2705 I get a crash error when I'm accompanied by other players. As I saw in the Repoerte, it does not render the skins well and there lies the problem. Here is the Crash. SAlu2s
[crash-2018-07-19_21.04.36-client.txt](https://github.com/DNAlchemist/ssskins/files/2218070/crash-2018-07-19_21.04.36-client.txt)

**Comment by DNAlchemist** [comment]
Fixed in 5ce07abfe155cc340423e4de24ac8d0277a36933, released in v0.0.2
