### ISSUE TITLE
Request - Relocate mod configuration

### ISSUE THREAD

**Issue by xsharov** [DNAlchemist/minecraft-skinny#5]
Can you relocate mod configuration in /config path?

A large number of small servers do not use dedicated servers to host their servers.
Instead, they use the services of various sites that provide ftp access and a web management interface.
In web management interfaces, there is often no access to custom parameters of the server.properties file and this file is overwritten every time the server starts, which removes the configuration line of this mod.
Moving the configuration to the /config folder will not only be a solution for this unpleasant problem, but also the best modding practices

**Comment by xsharov** [comment]
Fixed location in the commit
https://github.com/DNAlchemist/ssskins/pull/6

Can you build new version?

**Comment by DNAlchemist** [comment]
Try it. I had to download it through the curseforge UI, because the curseforge API responds with 503. I haven't figured out why yet.

**Comment by DNAlchemist** [comment]
Try it. I had to upload it through the curseforge UI, because the curseforge API responds with 503. I haven't figured out why yet.

**Comment by xsharov** [comment]
I already build it for myself a week ago
But i hope it will be usefull for other peolpe
Thanks you for this mod!
