### ISSUE TITLE
The mod doesn't work

### ISSUE THREAD

**Issue by ensvrd** [DNAlchemist/minecraft-skinny#8]
Forge 14.23.5.2854
Minecraft: 1.12.2
Specified ssskins-url=http://raw.githubusercontent.com/ensvrd/Minecraft-Skins/master/ and put skins in that repo Ex: https://raw.githubusercontent.com/ensvrd/Minecraft-Skins/master/Croshed.png
But Neither my skin shows up nor i see an output to the cmd

**Comment by ensvrd** [comment]
And when on my local world I'm still Steve so mod works but can't establish connection with link I think?

**Comment by ensvrd** [comment]
Well got through some java stuff and found out Minecraftskins link is hardcoded in server&client proxy

**Comment by ensvrd** [comment]
It fixed itself lol

**Comment by DNAlchemist** [comment]
Can you tell what you faced and how you solved it? it might help other users.
And I'll update the documentation if anything is missing.
