### ISSUE TITLE
Requires SSSkins 0.0.1 which is not found on the client. [using V. 0.0.4 on Server]

### ISSUE THREAD

**Issue by HiveMynd148** [DNAlchemist/minecraft-skinny#9]
When Joining the Server, the game gives me a error saying "Requires SSSkins 0.0.1 which is not found on the client" while I am using V. 0.0.4 on the Server. And I cannot find v. 0.0.1 Anywhere. Pls help

**Comment by DNAlchemist** [comment]
Did you solve that?
